### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Italofoschi** [ilyasbelfar/Outlook-Account-Creator#2]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Outlook-Account-Creator-main\main.py", line 214, in <module>
    driver = Prepare_Env(proxy)
  File "C:\Users\Administrator\Desktop\Outlook-Account-Creator-main\main.py", line 100, in Prepare_Env
    driver = webdriver.Chrome(options=options)
  File "C:\Users\Administrator\Desktop\Outlook-Account-Creator-main\venv\lib\site-packages\undetected_chromedriver\__init__.py", line 431, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\Administrator\Desktop\Outlook-Account-Creator-main\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__
    super().__init__(
  File "C:\Users\Administrator\Desktop\Outlook-Account-Creator-main\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\Administrator\Desktop\Outlook-Account-Creator-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Administrator\Desktop\Outlook-Account-Creator-main\venv\lib\site-packages\undetected_chromedriver\__init__.py", line 693, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\Administrator\Desktop\Outlook-Account-Creator-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Administrator\Desktop\Outlook-Account-Creator-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\Desktop\Outlook-Account-Creator-main\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: unrecognized chrome option: excludeSwitches
Stacktrace:
Backtrace:
	(No symbol) [0x00A36643]
	(No symbol) [0x009CBE21]
	(No symbol) [0x008CDA9D]
	(No symbol) [0x008E7213]
	(No symbol) [0x008EA110]
	(No symbol) [0x008E3993]
	(No symbol) [0x0092588A]
	(No symbol) [0x009253A0]
	(No symbol) [0x0092670C]
	(No symbol) [0x0092655C]
	(No symbol) [0x0091FB76]
	(No symbol) [0x008F49C1]
	(No symbol) [0x008F5E5D]
	GetHandleVerifier [0x00CAA142+2497106]
	GetHandleVerifier [0x00CD85D3+2686691]
	GetHandleVerifier [0x00CDBB9C+2700460]
	GetHandleVerifier [0x00AE3B10+635936]
	(No symbol) [0x009D4A1F]
	(No symbol) [0x009DA418]
	(No symbol) [0x009DA505]
	(No symbol) [0x009E508B]
	BaseThreadInitThunk [0x773605C9+25]
	RtlGetAppContainerNamedObjectPath [0x7795784D+237]
	RtlGetAppContainerNamedObjectPath [0x7795781D+189]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Outlook-Account-Creator-main\main.py", line 228, in <module>
    driver.close()
NameError: name 'driver' is not defined
invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: unrecognized chrome option: excludeSwitches

Process finished with exit code 1

**Comment by ilyasbelfar** [comment]
Fixed!
Try again with reading README file carefully.
